<?php

ob_start();

error_reporting(0);

include_once("lib_panel/config.php");





$todaydt=explode("-",$_POST[endt]);

$presentyr=$todaydt[0];

$month_dtls=$my->total_row($con,month_list,month_id,$todaydt[1]);

$first_date=$presentyr."-".$_POST[month_id]."-01";

$end_date= date("Y-m-t", strtotime($first_date));





if($_SESSION[employee_id]!=""){

$emp_dtls=$my->total_row($con,employee,employee_id,$_SESSION[employee_id]);

$gen_details=$emp_dtls[employee_name];

}else{

$gen_details="Chief Admim";

}



?>



<!DOCTYPE html>

<html>

<head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

<title>Employee TDS of <?=$month_dtls[month_name]?> <?=$presentyr?></title>

<link rel="stylesheet" type="text/css" href="jscss/datatables.min.css">

<script type="text/javascript" src="jscss/datatables.min.js"></script>

<meta name="viewport" content="width=device-width, initial-scale=1">

<style>

body {

font-size: 16px !important;

line-height: 25px !important;

}

</style>



</head>

<body class="">



<div class="container" style="min-height:500px;">



<div class="container" style="padding:20px;20px;">

<div class="">

<h1>Employee TDS for the month of <?=$month_dtls[month_name]?> <?=$presentyr?></h1>



<div class="">

<div id="employee_grid_wrapper" class="dataTables_wrapper">



<table id="employee_grid" class="display dataTable" width="100%" cellspacing="0" role="grid" aria-describedby="employee_grid_info" style="width: 100%;">

<thead>

<tr role="row">

<th style='font-size:12px;border:1px solid black;font-weight:bold;text-align:center'>Sr</td>

<th style='font-size:12px;border:1px solid black;font-weight:bold;text-align:center'>Name</td>

<th style='font-size:12px;border:1px solid black;font-weight:bold;text-align:center'>PAN</td>

<th style='font-size:12px;border:1px solid black;font-weight:bold;text-align:center'>TDS</td>

<th style='font-size:12px;border:1px solid black;font-weight:bold;text-align:center'>Net Amount</td>

</tr>

</thead>





<tbody>







<? 



$sel1 = "select * from `employee_salary` where `endt`='$_POST[endt]' AND `total_amt`!='0' ORDER BY `employee_id` ASC";

$res_pay = mysqli_query($con,$sel1);

while($row_pay = mysqli_fetch_array($res_pay)) { 

$c++;





$employee_dtls=$my->total_row($con,employee,employee_id,$row_pay[employee_id]);

$bank_dtls=$my->total_row($con,bank,bank_id,$employee_dtls[bank_id]);





$td+=$row_pay['td'];

$total_amt+=$row_pay['total_amt'];



?>

<tr>

<td style='font-size:12px;border:1px solid black;'><?=$c?>.</td>

<td style='font-size:12px;border:1px solid black;text-transform:uppercase'><?=$employee_dtls['employee_name']?></td>

<td style='font-size:12px;border:1px solid black;text-transform:uppercase'><?=$employee_dtls['employee_pan']?></td>

<td style='font-size:12px;border:1px solid black;text-transform:uppercase'><?=$row_pay['td']?></td>

<td style='font-size:12px;border:1px solid black;text-transform:uppercase'><?=$row_pay['total_amt']?></td>

</tr>	

<?} ?>



<tr>

<td style='font-size:12px;border:1px solid black;'>Total</td>

<td style='font-size:12px;border:1px solid black;'></td>

<td style='font-size:12px;border:1px solid black;'></td>

<td style='font-size:12px;border:1px solid black;text-transform:uppercase'><?=$td?></td>

<td style='font-size:12px;border:1px solid black;text-transform:uppercase'><?=$total_amt?></td>

</tr>



</tbody>





</table>



<h4>Report Generated By  <?=$gen_details?>	</h4>

<center> <a style='text-decoration:none;font-size:20px'  href="employee_salary_list.php?lid=<?=$_REQUEST[lid]?>">BACK</a> </center>



</div>

</div>

</div>



</div>





</div>





<script type="text/javascript">

$( document ).ready(function() {

$('#employee_grid').DataTable({

"processing": true,

"dom": 'lBfrtip',

"buttons": [

{

extend: 'collection',

text: 'Export',

buttons: [

'excel',

'csv',

'pdf',

'print'

]

}

]

});

});

</script>

</body>

</html>



