<?php
ob_start();
error_reporting(0);
include("include/loginchk.php");
include_once("lib_panel/config.php");

if(time() - $_SESSION['timestamp'] > 3600) { //subtract new timestamp from the old one

echo "<script>alert('30 minutes over');</script>";
unset($_SESSION[indi_cpanel]);
unset($_SESSION[login_type]);
unset($_SESSION[userid]);
unset($_SESSION[employee_id]);
unset($_SESSION[timestamp]);
session_destroy();
echo '<META HTTP-EQUIV="Refresh" Content="0; URL=index.php?msg=Login First">';		 
exit;
} else {
$_SESSION['timestamp'] = time(); //set new timestamp
}





if($_SESSION[employee_id]!=""){
$emp_dtls=$my->total_row($con,employee,employee_id,$_SESSION[employee_id]);
$gen_details=$emp_dtls[employee_name];
}else{
$gen_details="Chief Admim";
}



?>



<!DOCTYPE html>

<html>

<head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

<title>Employee Details</title>

<link rel="stylesheet" type="text/css" href="jscss/datatables.min.css">

<script type="text/javascript" src="jscss/datatables.min.js"></script>

<meta name="viewport" content="width=device-width, initial-scale=1">

<style>

body {

font-size: 16px !important;

line-height: 25px !important;

}

</style>



</head>

<body class="">



<div class="container" style="min-height:500px;">



<div class="container" style="padding:20px;20px;">

<div class="">

<h1>Employee Details</h1>



<div class="">

<div id="employee_grid_wrapper" class="dataTables_wrapper">



<table id="employee_grid" class="display dataTable" width="100%" cellspacing="0" role="grid" aria-describedby="employee_grid_info" style="width: 100%;">

<thead>

<tr role="row">

<th style='font-size:12px;border:1px solid black;font-weight:bold;text-align:center'>Sr</td>

<th style='font-size:12px;border:1px solid black;font-weight:bold;text-align:center'>ID</td>

<th style='font-size:12px;border:1px solid black;font-weight:bold;text-align:center'>Name</td>

<th style='font-size:12px;border:1px solid black;font-weight:bold;text-align:center'>S/O</td>

<th style='font-size:12px;border:1px solid black;font-weight:bold;text-align:center'>Mobile No</td>

<th style='font-size:12px;border:1px solid black;font-weight:bold;text-align:center'>Designation</td>

<th style='font-size:12px;border:1px solid black;font-weight:bold;text-align:center'>Address</td>

<th style='font-size:12px;border:1px solid black;font-weight:bold;text-align:center'>Pincode</td>

<th style='font-size:12px;border:1px solid black;font-weight:bold;text-align:center'>Salary</td>

</tr>

</thead>





<tbody>







<? 

if($_POST[emp_search]==1){

$sel1 = "select * from `employee` where `employee_code` ='$_POST[employee_code]' ";

}else{

$sel1 = "select * from `employee` ORDER BY `employee_id` ASC";

}

$res_pay = mysqli_query($con,$sel1);

while($row_pay = mysqli_fetch_array($res_pay)) { 

$c++;



$designation_dtls=$my->total_row($con,designation,designation_id,$row_pay[designation_id]);



if($row_pay[st]==1){

$msg="<span style='color:green'>Active</span>";

}else{

$msg="<span style='color:green'>In Active</span>";

}

?>

<tr>

<td style='font-size:12px;border:1px solid black;'><?=$c?>.</td>

<td style='font-size:12px;border:1px solid black;'><?=$row_pay['employee_code']?></td>

<td style='font-size:12px;border:1px solid black;text-transform:uppercase'><?=$row_pay['employee_name']?></td>

<td style='font-size:12px;border:1px solid black;text-transform:uppercase'><?=$row_pay['employee_father']?></td>

<td style='font-size:12px;border:1px solid black;'><?=$row_pay['employee_mobile']?></td>

<td style='font-size:12px;border:1px solid black;text-transform:uppercase'><?=$designation_dtls['designation_name']?></td>

<td style='font-size:12px;border:1px solid black;text-transform:uppercase'><?=$row_pay['employee_address']?></td>

<td style='font-size:12px;border:1px solid black;text-transform:uppercase'><?=$row_pay['employee_pincode']?></td>

<td style='font-size:12px;border:1px solid black;'><?=$row_pay['employee_salary']?></td>

</tr>	

<?} ?>







</tbody>





</table>



<h4>Report Generated By  <?=$gen_details?>	</h4>

<center> <a style='text-decoration:none;font-size:20px'  href="employee_report.php?lid=<?=$_REQUEST[lid]?>">BACK</a> </center>



</div>

</div>

</div>



</div>





</div>





<script type="text/javascript">

$( document ).ready(function() {

$('#employee_grid').DataTable({

"processing": true,

"dom": 'lBfrtip',

"buttons": [

{

extend: 'collection',

text: 'Export',

buttons: [

'excel',

'csv',

'pdf',

'print'

]

}

]

});

});

</script>

</body>

</html>



