<!DOCTYPE html>
<html lang="en">


<?php
include_once("include/header_top.php");
?>

<body class="hold-transition sidebar-mini">
<!--preloader-->
<div id="preloader">
<div id="status"></div>
</div>

<?
$endt=$_REQUEST[end_date];
$stdt=$_REQUEST[start_date];
?>







<!-- Site wrapper -->
<div class="wrapper">
<?php
include_once("include/header_down.php");
?>
<!-- =============================================== -->
<!-- Left side column. contains the sidebar -->
<?php
include_once("include/menu.php");
?>

<!-- =============================================== -->
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
<!-- Content Header (Page header) -->
<section class="content-header">
<div class="header-icon"><i class="fa fa-shopping-basket"></i></div>

<div class="header-title">
<h1>Package - E-Pin</h1>
<small>UnUsed E-Pin Details</small>
</div>
</section>
<!-- Main content -->
<section class="content">
<div class="row">

<div class="col-sm-12">
<div class="panel lobidisable panel-bd">
<div style="padding:10px;color: #010611;background-color: #e8f1f3;border-color: #b7b9bf;position: relative;">
<div class="panel-title">
<h4>UnUsed E-Pin Details</h4>
</div>
</div>

<?php
if($_GET[pg])
{
$pg=$_GET[pg];
}
else
{
$pg=1;
}
$upper=50;
$lower=$upper*($pg-1);
$sql9="select * from `e-pin` WHERE `date`>='$stdt' and `date`<='$endt'  `pin_type`!='franchise'";
$res9=mysqli_query($con,$sql9);
$num9=mysqli_num_rows($res9);
$pgno=intval($num9/$upper);
if($num9%$upper!=0)
{
$pgno=$pgno+1;
}

?>



<div class="panel-body">
<div class="table-responsive">
<table class="table table-bordered table-hover">
<thead>
<tr class="info">

<th>No.</th>
<th>Sr.No.</th>
<th>Pin No.</th>
<th>Generated By</th>
<th>Package</th>
<th>Type</th>
<th>Date</th>
<th>status</th>
<th>Transfer ID</th>


</tr>
</thead>
<tbody>
<?
$sql="SELECT * FROM `e-pin` WHERE `date`>='$stdt' and `date`<='$endt'  ORDER BY `id` DESC  limit $lower,$upper";
$res=mysqli_query($con,$sql);
while($row=mysqli_fetch_array($res)){
$c++;
if($row[status]==1){$st="Unused";}
if($row[status]==0){$st="Used";}
$sre="SELECT * FROM `package` WHERE `package_id`='$row[package_id]'";
$ret=mysqli_query($con,$sre);
$des=mysqli_fetch_array($ret);

if($des[package_type]==1){ $pmsg="Join";}
if($des[package_type]==2){ $pmsg="Repurchase";}
if($des[package_type]==3){ $pmsg="Power";}



?>

<tr>
<td><?=$c?></td>


<td><?=$row[id]?></td>
<td><?=$row[pin]?></td>
<td><?=$row[generatedid]?></td>
<td><?=$des[package_name]?></td>
<td><?=$pmsg?></td>
<td><?=$row['date']?></td>
<td><?=$st?></td>
<td><?=$row[memtransid]?></td>

</tr>

<? } ?>

</tbody>
</table>

<div class="pagination">
<?
$pre=$pg-1;
$nxt=$pg+1;

if($pg!=1)
print "<A HREF='unused_epin.php?pg=$pre&lid=$dtls_link[sublink_id]'class='previous-off'>&laquo; Previous</A>";
else
print "<span class='previous-off'>&laquo; Previous</span>";



for($i=1;$i<=$pgno;$i++)
{
if($i!=$pg)
print "&nbsp;&nbsp;&nbsp;&nbsp;<A HREF='unused_epin.php?pg=$i&lid=$dtls_link[sublink_id]'>$i</A>";
else
print "&nbsp;&nbsp;&nbsp;&nbsp;$i";
}

if($pg!=$pgno)
print "&nbsp;&nbsp;&nbsp;&nbsp;<A HREF='unused_epin.php?pg=$nxt&lid=$dtls_link[sublink_id]'class='next'>Next &raquo;</A>";
else
print "&nbsp;&nbsp;&nbsp;&nbsp;<span class='next'>Next &raquo;</span>";
?>
</div>


</div>
</div>
</div>
</div>
</div>
</section>




<!-- /.content -->
</div>
<!-- /.content-wrapper -->
<?php
include_once("include/footer_top.php");
?>
</div>
<!-- /.wrapper -->
<!-- Start Core Plugins
=====================================================================-->
<?php
include_once("include/footer_down.php");
?>

</body>

</html>
