<!DOCTYPE html>
<html lang="en">


<?php
include_once("include/header_top.php");
?>

<body class="hold-transition sidebar-mini">
<!--preloader-->
<div id="preloader">
<div id="status"></div>
</div>

<?



?>







<!-- Site wrapper -->
<div class="wrapper">
<?php
include_once("include/header_down.php");
?>
<!-- =============================================== -->
<!-- Left side column. contains the sidebar -->
<?php
include_once("include/menu.php");
?>

<!-- =============================================== -->
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
<!-- Content Header (Page header) -->
<section class="content-header">
<div class="header-icon"><i class="fa fa-shopping-basket"></i></div>

<div class="header-title">
<h1>Package - E-Pin</h1>
<small>Used E-Pin Details</small>
</div>
</section>
<!-- Main content -->
<section class="content">
<div class="row">

<div class="col-sm-12">
<div class="panel lobidisable panel-bd">
<div style="padding:10px;color: #010611;background-color: #e8f1f3;border-color: #b7b9bf;position: relative;">
<div class="panel-title">
<h4>Used E-Pin Details</h4>
</div>
</div>

<?php
if($_GET[pg])
{
$pg=$_GET[pg];
}
else
{
$pg=1;
}
$upper=50;
$lower=$upper*($pg-1);
$sql9="select * from `e-pin` WHERE `status`='0'";
$res9=mysqli_query($con,$sql9);
$num9=mysqli_num_rows($res9);
$pgno=intval($num9/$upper);
if($num9%$upper!=0)
{
$pgno=$pgno+1;
}

?>



<div class="panel-body">
<div class="table-responsive">
<table class="table table-bordered table-hover">
<thead>
<tr class="info">


<th>Sr No.</th>
<th>Pin No.</th>
<th>Generated By</th>
<th>Generated Date</th>
<th>Package</th>
<!--<th>Type</th>-->
<th>Transfer ID</th>
<th>Used ID</th>
<th>Used Date</th>

</tr>
</thead>
<tbody>
<?php
$sql="SELECT * FROM `e-pin` WHERE `status`='0' ORDER BY `id` ASC  limit $lower,$upper";
$res=mysqli_query($con,$sql);
while($row=mysqli_fetch_array($res)){
$c++;

$sre="SELECT * FROM `package` WHERE `package_id`='$row[package_id]'";
$ret=mysqli_query($con,$sre);
$des=mysqli_fetch_array($ret);	

if($des[package_type]==1){ $pmsg="TopUp";} 
if($des[package_type]==2){ $pmsg="Repurchase";} 
if($des[package_type]==3){ $pmsg="Royalty";} 


?>

<tr>



<td align="center"><?=$row[id]?></td>
<td><?=$row[pin]?></td>
<td><?=$row[generatedid]?></td>
<td><?=$row['date']?></td>
<td><?=$des[package_name]?></td>
<td><?=$row[memtransid]?></td>
<td><?=$row[memberusedid]?></td>
<td><?=$row[useddate]?></td>
</tr>

<? } ?>

</tbody>
</table>

<div class="pagination">
<?
$pre=$pg-1;
$nxt=$pg+1;

if($pg!=1)
print "<A HREF='used_epin.php?pg=$pre&lid=$dtls_link[sublink_id]'class='previous-off'>&laquo; Previous</A>";
else
print "<span class='previous-off'>&laquo; Previous</span>";



for($i=1;$i<=$pgno;$i++)
{
if($i!=$pg)
print "&nbsp;&nbsp;&nbsp;&nbsp;<A HREF='used_epin.php?pg=$i&lid=$dtls_link[sublink_id]'>$i</A>";
else
print "&nbsp;&nbsp;&nbsp;&nbsp;$i";
}

if($pg!=$pgno)
print "&nbsp;&nbsp;&nbsp;&nbsp;<A HREF='used_epin.php?pg=$nxt&lid=$dtls_link[sublink_id]'class='next'>Next &raquo;</A>";
else
print "&nbsp;&nbsp;&nbsp;&nbsp;<span class='next'>Next &raquo;</span>";
?> 
</div>  


</div>
</div>
</div>
</div>
</div>
</section>




<!-- /.content -->
</div>
<!-- /.content-wrapper -->
<?php
include_once("include/footer_top.php");
?>
</div>
<!-- /.wrapper -->
<!-- Start Core Plugins
=====================================================================-->
<?php
include_once("include/footer_down.php");
?>

</body>

</html>
